<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-19T01:58:48 IST" name="InetBankingV1" finished-at="2022-10-19T02:00:03 IST" duration-ms="74921">
    <groups>
    </groups>
    <test started-at="2022-10-19T01:58:48 IST" name="BankingApp Test" finished-at="2022-10-19T02:00:03 IST" duration-ms="74921">
      <class name="com.InetBanking.testCases.TC_LoginDDT_02">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:06 IST" name="Setup" finished-at="2022-10-19T01:59:10 IST" duration-ms="4672" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:12 IST" name="LoginDDT" data-provider="LoginData" finished-at="2022-10-19T01:59:17 IST" duration-ms="5774" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr449147]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tyvUbuv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:17 IST" name="LoginDDT" data-provider="LoginData" finished-at="2022-10-19T01:59:22 IST" duration-ms="4901" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mgr439974]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[agbcDhj]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.InetBanking.testCases.TC_LoginDDT_02.LoginDDT(TC_LoginDDT_02.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:22 IST" name="LoginDDT" data-provider="LoginData" finished-at="2022-10-19T01:59:29 IST" duration-ms="6407" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr449147]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tyvUbuv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:29 IST" name="LoginDDT" data-provider="LoginData" finished-at="2022-10-19T01:59:34 IST" duration-ms="4983" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mnr439975]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[xyzBcmc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.InetBanking.testCases.TC_LoginDDT_02.LoginDDT(TC_LoginDDT_02.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.InetBanking.testCases.TC_LoginDDT_02@22ef9844]" started-at="2022-10-19T01:59:34 IST" name="tearDown" finished-at="2022-10-19T01:59:34 IST" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.InetBanking.testCases.TC_LoginDDT_02 -->
      <class name="com.InetBanking.testCases.TC_LoginTest_01">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com.InetBanking.testCases.TC_LoginTest_01@4229bb3f]" started-at="2022-10-19T01:58:49 IST" name="Setup" finished-at="2022-10-19T01:58:54 IST" duration-ms="4908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="LoginTest()[pri:0, instance:com.InetBanking.testCases.TC_LoginTest_01@4229bb3f]" started-at="2022-10-19T01:58:54 IST" name="LoginTest" finished-at="2022-10-19T01:59:05 IST" duration-ms="11738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.InetBanking.testCases.TC_LoginTest_01@4229bb3f]" started-at="2022-10-19T01:59:05 IST" name="tearDown" finished-at="2022-10-19T01:59:06 IST" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.InetBanking.testCases.TC_LoginTest_01 -->
      <class name="com.InetBanking.testCases.TC_AddCustomerTest_03">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com.InetBanking.testCases.TC_AddCustomerTest_03@6283d8b8]" started-at="2022-10-19T01:59:34 IST" name="Setup" finished-at="2022-10-19T01:59:38 IST" duration-ms="4504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="AddNewCustomer()[pri:0, instance:com.InetBanking.testCases.TC_AddCustomerTest_03@6283d8b8]" started-at="2022-10-19T01:59:38 IST" name="AddNewCustomer" finished-at="2022-10-19T02:00:03 IST" duration-ms="24552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddNewCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.InetBanking.testCases.TC_AddCustomerTest_03@6283d8b8]" started-at="2022-10-19T02:00:03 IST" name="tearDown" finished-at="2022-10-19T02:00:03 IST" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.InetBanking.testCases.TC_AddCustomerTest_03 -->
    </test> <!-- BankingApp Test -->
  </suite> <!-- InetBankingV1 -->
</testng-results>
